image: vsbuildci:latest

stages:
    - restore
    - build
    
restore:
    stage: restore
    script:
        - msbuild MatrixUWP/MatrixUWP.csproj /t:restore /m
    tags: ["windows"]
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - MatrixUWP/obj
            - MatrixUWP.Test/obj

build-debug:
    stage: build
    only:
        - develop
    script:
        - msbuild MatrixUWP/MatrixUWP.csproj /p:Configuration=Debug /p:AppxBundlePlatforms="x86|x64|ARM" /p:AppxPackageDir="AppxPackages" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /m
    tags: ["windows"]

build-release:
    stage: build
    only:
        - master
    script:
        - msbuild MatrixUWP/MatrixUWP.csproj /p:Configuration=Release /p:AppxBundlePlatforms="x86|x64|ARM|ARM64" /p:AppxPackageDir="AppxPackages" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /m
    tags: ["windows"]
    artifacts:
      paths:
        - AppxPackages
