image: vsbuildci:latest

cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
        - packages

stages:
    - build

build-debug:
    stage: build
    only:
        - develop
    script:
        - msbuild MatrixUWP/MatrixUWP.csproj /t:restore /m /verbosity:m
        - msbuild MatrixUWP/MatrixUWP.csproj /p:Configuration=Debug /p:AppxBundlePlatforms="x86|x64|ARM" /p:AppxPackageDir=AppxPackages /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:DefineConstants="TRACE DEBUG NETFX_CORE WINDOWS_UWP" /m /verbosity:m
    tags: ["windows"]
    artifacts:
      paths:
        - MatrixUWP/AppxPackages

build-release:
    stage: build
    only:
        - master
    script:
        - msbuild MatrixUWP/MatrixUWP.csproj /t:restore /m /verbosity:m
        - msbuild MatrixUWP/MatrixUWP.csproj /p:Configuration=Release /p:AppxBundlePlatforms="x86|x64|ARM|ARM64" /p:AppxPackageDir=AppxPackages /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /m /verbosity:m
    tags: ["windows"]
    artifacts:
      paths:
        - MatrixUWP/AppxPackages
